### ISSUE TITLE
Default Options like h265ize?

### ISSUE THREAD

**Issue by marshalleq** [NMMES/nmmes-cli#12]
Coming from your other, super and very nice tool (should be standard in ALL linux distro's I think), this is a little more complicated.  After a few scans, I can't see how to NOT normalise my audio, which I really don't want to do, nor can I see how to set h265, medium, 23.  That's all I need, but bugs in the subtitle processing of h265ize are now preventing me from using that too.

Maybe add to an FAQ?

Thanks.

**Comment by FallingSnow** [comment]
Yeah, I haven't had a lot of time to spend on NMMES & h265ize in the last year unfortunately so they are both very buggy :/.

To not normalize your audio don't use the `normalize` module (it's enabled by default). Use the `--modules` flag to define the modules you want to use. For example you might want to only use the encoder module: `nmmes-cli --modules encoder video.mkv`. The `--help` flag works based of the modules defined by the `--modules` flag. So if you want to display help information about the normalization module you would use `nmmes-cli --modules normalize --help`.

To use h265, medium, crf 23 you would use `nmmes-cli --modules encoder --encoder-preset medium --encoder-quality 23 --video-codec libx265 videos/`.

*This is all off memory so lemme know if it doesn't work.*

> Maybe add to an FAQ?

NMMES still isn't even half way finished so that would be after I finalize at least the CLI interface.

**Comment by marshalleq** [comment]
OK, so to not have a default enabled, you simply specify other ones, not what I was guessing, but good to know.  I loved that you had the foresight to not mess with the sound in the h265ize - it had a single purpose and did it well, not to mention with no parameters necessary.  Good marketing - hope you get a bit more time this year for completely selfish reasons! LOL
